import Foundation

/// Where the bundled dataset came from. Decoded from the runtime asset
/// rather than hard-coded in the app, so the credits the app shows are
/// generated by the same tool that generated the geometry and cannot
/// drift away from it.
public struct DatasetProvenance: Equatable, Sendable, Codable {
    public let geometrySource: String
    public let geometrySourceURL: String
    public let geometryVersion: String
    public let geometryLicense: String
    public let metadataSource: String
    public let metadataSourceURL: String
    public let metadataVersion: String
    public let metadataLicense: String
    public let imagerySource: String
    public let imagerySourceURL: String
    public let imageryLicense: String
    public let imageryAttribution: String
    public let attribution: String
    /// Steps the generator applied to the source data.
    public let transformations: [String]
    public let generatedAt: String
    public let countryCount: Int

    public init(
        geometrySource: String,
        geometrySourceURL: String,
        geometryVersion: String,
        geometryLicense: String,
        metadataSource: String,
        metadataSourceURL: String,
        metadataVersion: String,
        metadataLicense: String,
        imagerySource: String,
        imagerySourceURL: String,
        imageryLicense: String,
        imageryAttribution: String,
        attribution: String,
        transformations: [String],
        generatedAt: String,
        countryCount: Int
    ) {
        self.geometrySource = geometrySource
        self.geometrySourceURL = geometrySourceURL
        self.geometryVersion = geometryVersion
        self.geometryLicense = geometryLicense
        self.metadataSource = metadataSource
        self.metadataSourceURL = metadataSourceURL
        self.metadataVersion = metadataVersion
        self.metadataLicense = metadataLicense
        self.imagerySource = imagerySource
        self.imagerySourceURL = imagerySourceURL
        self.imageryLicense = imageryLicense
        self.imageryAttribution = imageryAttribution
        self.attribution = attribution
        self.transformations = transformations
        self.generatedAt = generatedAt
        self.countryCount = countryCount
    }
}

/// A loaded, validated dataset: countries, their provenance, and a
/// ready-built lookup. Immutable once loaded.
public struct GeographyDataset: Sendable {
    public let countries: [Country]
    public let provenance: DatasetProvenance
    public let lookup: CountryLookup

    public init(countries: [Country], provenance: DatasetProvenance) {
        self.countries = countries
        self.provenance = provenance
        self.lookup = CountryLookup(countries: countries)
    }
}

/// Failures that can stop the globe from loading. Each case carries
/// enough detail for the UI to show something actionable — the point of
/// FR-12 is that a missing resource never becomes a blank window.
public enum GeographyError: Error, Equatable, LocalizedError, Sendable {
    case resourceMissing(name: String)
    case resourceUnreadable(name: String, reason: String)
    case malformedData(reason: String)
    case unsupportedFormatVersion(found: Int, supported: Int)
    case emptyDataset

    public var errorDescription: String? {
        switch self {
        case .resourceMissing(let name):
            return "The bundled geography data “\(name)” is missing from the app."
        case .resourceUnreadable(let name, _):
            return "The bundled geography data “\(name)” could not be read."
        case .malformedData:
            return "The bundled geography data is not in the expected format."
        case .unsupportedFormatVersion(let found, let supported):
            return "The bundled geography data uses format version \(found); this build supports version \(supported)."
        case .emptyDataset:
            return "The bundled geography data contains no countries."
        }
    }

    public var failureReason: String? {
        switch self {
        case .resourceUnreadable(_, let reason):
            return reason
        case .malformedData(let reason):
            return reason
        default:
            return nil
        }
    }

    public var recoverySuggestion: String? {
        switch self {
        case .resourceMissing, .resourceUnreadable:
            return "Reinstall Atlas Desktop, or rebuild it from source after running Tools/fetch-source-data.sh and “swift run AtlasDataTool”."
        case .malformedData, .unsupportedFormatVersion, .emptyDataset:
            return "Regenerate the bundled data with “swift run AtlasDataTool” and rebuild."
        }
    }
}

/// Loads the bundled dataset. A protocol so the app can be driven by a
/// fixture repository in tests, including deliberately failing ones.
public protocol GeographyRepository: Sendable {
    func load() async throws -> GeographyDataset
}

/// A repository backed by values already in memory — fixtures in tests,
/// and the seam that lets a UI test inject a dataset or a failure.
public struct StaticGeographyRepository: GeographyRepository {
    private let result: Result<GeographyDataset, GeographyError>

    public init(dataset: GeographyDataset) { self.result = .success(dataset) }
    public init(failure: GeographyError) { self.result = .failure(failure) }

    public func load() async throws -> GeographyDataset {
        try result.get()
    }
}
