import Foundation
import AtlasDesktopCore

/// The on-disk shape of the bundled runtime asset.
///
/// Deliberately a flat, boring format: ring coordinates are stored as a
/// single `[Double]` of interleaved longitude/latitude pairs rather than
/// nested pairs, which roughly halves the file and decodes in one pass.
/// It is generated by `AtlasDataTool` from the files in `Data/source`
/// and is never fetched at runtime.
///
/// `formatVersion` is checked on load: a newer asset than the app
/// understands is a hard error rather than a partial read.
public struct RuntimeDataset: Codable, Sendable {
    public static let supportedFormatVersion = 1

    public let formatVersion: Int
    public let provenance: DatasetProvenance
    public let countries: [RuntimeCountry]

    public init(formatVersion: Int = RuntimeDataset.supportedFormatVersion, provenance: DatasetProvenance, countries: [RuntimeCountry]) {
        self.formatVersion = formatVersion
        self.provenance = provenance
        self.countries = countries
    }
}

public struct RuntimeCountry: Codable, Sendable {
    /// Natural Earth `ADM0_A3`. Present for every source feature, which
    /// `ISO_A3` is not.
    public let id: String
    public let name: String
    public let longName: String?
    public let iso2: String?
    public let iso3: String?
    public let continent: String?
    public let region: String?
    public let subregion: String?
    public let capitals: [String]
    public let labelLatitude: Double
    public let labelLongitude: Double
    public let polygons: [RuntimePolygon]

    public init(
        id: String,
        name: String,
        longName: String?,
        iso2: String?,
        iso3: String?,
        continent: String?,
        region: String?,
        subregion: String?,
        capitals: [String],
        labelLatitude: Double,
        labelLongitude: Double,
        polygons: [RuntimePolygon]
    ) {
        self.id = id
        self.name = name
        self.longName = longName
        self.iso2 = iso2
        self.iso3 = iso3
        self.continent = continent
        self.region = region
        self.subregion = subregion
        self.capitals = capitals
        self.labelLatitude = labelLatitude
        self.labelLongitude = labelLongitude
        self.polygons = polygons
    }
}

public struct RuntimePolygon: Codable, Sendable {
    /// Interleaved `[lon, lat, lon, lat, …]`, no repeated closing
    /// vertex. The first ring is the outer boundary; the rest are holes.
    public let rings: [[Double]]

    public init(rings: [[Double]]) {
        self.rings = rings
    }
}
